Listen 443

# Redirección obligatoria HTTP → HTTPS (código 301 = permanente)
<VirtualHost *:80>
    ServerName localhost
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>

# VirtualHost HTTPS con certificado autofirmado
<VirtualHost *:443>
    ServerName localhost
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/nexorder.crt
    SSLCertificateKeyFile /etc/pki/tls/private/nexorder.key

    # Cabecera HSTS: obliga al navegador a usar HTTPS durante 1 año
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
</VirtualHost>